# Shared secrets file - link to this file rather than copying!
# /service-config/iot-home/.secrets.yml

# Example:

# Time Zone
time_zone: "America/Los_Angeles"

# wifi
wifi_ssid: MY_WIFI_SSID
wifi_pwd: MY_WIFI_PASSWORD
