balena-cli:
    build: .
    restart: unless-stopped
    privileged: true
    labels:
        io.balena.features.supervisor-api: 1
    environment:
        - JUPYTER_PORT=8891
        - SHELL=/bin/bash
    volumes:
        - iot-home:/home/iot
        - iot-home:/service-config/iot-home
        - config:/service-config/config
    expose:
        - 8891
    depends_on:
        - config
        # do not start early, may set wrong owner on .local
        - jupyter
