version: '2'

# located @ /mnt/data/docker/volumes
volumes:
    iot-home:
    code-server-config:
    duplicati-config:
    nginx-config:
    mosquitto-config:
    wireshark-config:

services:

    nginx:
        build: ./core/nginx
        restart: unless-stopped
        privileged: true
        labels:
            io.balena.features.supervisor-api: 1
        volumes:
            - iot-home:/home/iot
            - nginx-config:/etc/nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - micropython
            - code-server
            - duplicati
            - wireshark
            - arm32
            - esp-idf
            - balena-cli

    micropython:
        build: ./core/micropython
        restart: unless-stopped
        privileged: true
        # required for prototyping web services (e.g. httpd) and bluetooth
        network_mode: host
        labels:
            io.balena.features.dbus: 1
            io.balena.features.supervisor-api: 1
        environment:
            # for dbus-send
            - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
        volumes:
            - iot-home:/home/iot
            # never shadowed by cifs mount
            - iot-home:/service-config/iot-home
            - code-server-config:/service-config/code-server
            - duplicati-config:/service-config/duplicati
            - nginx-config:/service-config/nginx
            - mosquitto-config:/service-config/mosquitto
            - wireshark-config:/service-config/wireshark
        expose:
            - 8888
        depends_on:
            - smb

    # https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
    code-server:
        build: ./core/code-server
        restart: unless-stopped
        privileged: true
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - code-server-config:/config
            - iot-home:/config/workspace
            - iot-home:/service-config/iot-home
            - code-server-config:/service-config/code-server
            - duplicati-config:/service-config/duplicati
            - nginx-config:/service-config/nginx
            - mosquitto-config:/service-config/mosquitto
            - wireshark-config:/service-config/wireshark
        expose:
            - 8443
        depends_on:
            - smb

    duplicati:
        build: ./core/duplicati
        restart: unless-stopped
        privileged: true
        environment:
            - PUID=0
            - PGID=0
            - CLI_ARGS=--webservice-interface=any
        volumes:
            - duplicati-config:/config
            - iot-home:/service-config/iot-home
            - code-server-config:/service-config/code-server
            - duplicati-config:/service-config/duplicati
            - nginx-config:/service-config/nginx
            - mosquitto-config:/service-config/mosquitto
            - wireshark-config:/service-config/wireshark
        expose:
            - 8200

    smb:
        build: ./plugins/smb
        restart: unless-stopped
        privileged: true
        volumes:
            - iot-home:/home/iot
        ports:
            - 139:139
            - 445:445

    mosquitto:
        build: ./plugins/mosquitto
        restart: unless-stopped
        labels:
            io.balena.features.supervisor-api: 1
        volumes:
            - mosquitto-config:/mosquitto
        ports: 
            - 1883:1883  # mqtt
            - 9001:9001  # mqtt over websockets
            - 8883:8883  # secure mqtt
            - 9002:9002  # secure mqtt over websockets

    wireshark:
        image: linuxserver/wireshark:2.4.5
        # required to monitor docker network traffic
        network_mode: host
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - wireshark-config:/config
        expose:
            - 3000
      
    arm32:
        build: ./plugins/arm32
        restart: unless-stopped
        privileged: true
        volumes:
            - iot-home:/home/iot
            - iot-home:/service-config/iot-home
        environment:
            - JUPYTER_PORT=8889
        expose:
            - 8889
        depends_on:
            - smb

    # Soon for aarch64: https://github.com/espressif/esp-idf/issues/6432
    esp-idf:
        build: 
            context: ./plugins/esp-idf
            args:
                IDF_CHECKOUT_REF: v4.3.1
        restart: unless-stopped
        privileged: true
        volumes:
            - iot-home:/home/iot
            - iot-home:/service-config/iot-home
        environment:
            - JUPYTER_PORT=8890
        expose:
            - 8890
        depends_on:
            - smb
                        
    balena-cli:
        build: ./plugins/balena-cli
        restart: unless-stopped
        privileged: true
        labels:
            io.balena.features.supervisor-api: 1
        environment:
            - JUPYTER_PORT=8891
            - SHELL=/bin/bash
        volumes:
            - iot-home:/home/iot
            - iot-home:/service-config/iot-home
        expose:
            - 8891
        depends_on:
            # do not start early, may set wrong owner on .local
            - micropython
            - smb
