# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/

image: grafana/grafana-oss
restart: unless-stopped
# CONFLICT port 3000: grafana, libreoffice, winshark
# use only 1 in bridge mode at a time
http_port: 3000
volumes:
  - grafana:/var/lib/grafana
