# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      # port 3000 in use by wireshark
      - "3001:3000"
    volumes:
      - grafana:/var/lib/grafana
