# image: linuxserver/plex:latest
build: .
restart: unless-stopped
privileged: true
network_mode: host
volumes:
    - plex:/config
    # - media:/media
environment:
    - PUID=1000
    - PGID=100
    - VERSION=docker
    # - PLEX_CLAIM=claim-jifZ9RJFtLREjLDufCLn
http_port: 32400
