image: ubuntu:22.04
restart: unless-stopped
privileged: true
labels:
    io.balena.features.dbus: '1'
environment:
    # required for bluetooth
    - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
volumes:
    - iot-home:/home/iot
    {{ all_volumes() }}
