image: linuxserver/syncthing
environment:
    - PUID=1000
    - PGID=100
ports:
    # - 8384:8384
    - 22000:22000/tcp
    - 22000:22000/udp
    - 21027:21027/udp
http_port: 8384
restart: unless-stopped
volumes:
    - syncthing:/config
    {{ all_volumes() }}

