image: ttmetro/syncthing
# build: .
environment:
    - PUID=1000
    - PGID=100
    - TZ={{ secrets.time_zone }}
ports:
    # - 8384:8384
    - 22000:22000/tcp
    - 22000:22000/udp
    - 21027:21027/udp
http_port: 8384
restart: unless-stopped
volumes:
    - syncthing:/config
    # keep syncthing file list between container rebuilds
    - syncthing-foldermarker:/service-config
    - config:/service-config/config
    - iot-home:/service-config/iot-home
    - www:/service-config/www
    # - homeassistant:/service-config/homeassistant
    - esphome:/service-config/esphome
    - media:/service-config/media
