# image: jupyter/base-notebook
build: .
restart: unless-stopped
# network_mode: host
# privileged: true
labels:
    io.balena.features.supervisor-api: '1'
    io.balena.features.dbus: '1'
environment:
    - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    - 'UDEV=on'
ports:
    - 8888:8888
volumes:
    - iot-home:/home/iot
    {{ all_volumes() }}
