nginx:
    build: .
    restart: unless-stopped
    privileged: true
    labels:
        io.balena.features.supervisor-api: 1
    ports:
        - 80:80
        - 443:443
    depends_on:
        - config
        - jupyter
    volumes:
        - nginx:/etc/nginx
        - www:/service-config/www
