image: ttmetro/nginx
build: .
restart: unless-stopped
ports:
    - 80:80
    - 443:443
environment:
    - HTTP_PORTS={{ http_ports | tojson() | replace('\n', '') | replace(' ', '')}}
volumes:
    - www:/service-config/www
    - config:/service-config/config
depends_on:
    - config
    {{ all_servers() }}


