build: .
restart: unless-stopped
# privileged: true
labels:
    io.balena.features.supervisor-api: 1
ports:
    - 80:80
    - 443:443
environment:
    - HTTP_PORTS={{ http_ports | tojson() | replace('\n', '') | replace(' ', '')}}
volumes:
    # - nginx:/etc/nginx
    - www:/service-config/www
    - config:/service-config/config
depends_on:
    - config
