image: "postgres:14-alpine"
environment:
  - POSTGRES_DB={{ secrets.postgres_db }}
  - POSTGRES_USER={{ secrets.postgres_user }}
  - POSTGRES_PASSWORD={{ secrets.postgres_pwd }}
expose: 
  - 5432
restart: unless-stopped
volumes:
  - postgres:/var/lib/postgresql/data
