image: "postgres:14-alpine"
environment:
  - POSTGRES_DB={{ secrets.postgres_db }}
  - POSTGRES_USER={{ secrets.postgres_user }}
  - POSTGRES_PASSWORD={{ secrets.postgres_pwd }}
ports: 
  # homeassistant uses the db and cannot find it if it's not exposed to host
  - 5432:5432
restart: unless-stopped
volumes:
  - postgres:/var/lib/postgresql/data
