image: ttmetro/code-server
build: .
restart: unless-stopped
privileged: true
environment:
    - PUID=1000
    - PGID=100
volumes:
    - code-server:/config
    - iot-home:/config/workspace
    {{ all_volumes() }}
http_port: 8443
