duplicati:
    build: .
    restart: unless-stopped
    privileged: true
    environment:
        - PUID=0
        - PGID=0
        - CLI_ARGS=--webservice-interface=any
    volumes:
        - duplicati:/config
        - backup:/backup
        - ALL:/service-config
    expose:
        - 8200
