arm32:
    build: ./plugins/arm32
    restart: unless-stopped
    privileged: true
    volumes:
        - iot-home:/home/iot
        - iot-home:/service-config/iot-home
    environment:
        - JUPYTER_PORT=8889
    expose:
        - 8889
    depends_on:
        - smb