services:
  # --- web interface
  - config
  - nginx
  - mdns-publisher
  # --- apps
  # - jupyter
  # --- debugging
  # - base-notebook
  # - playground
  # - http-tester
  # - ubuntu


fleets:
  # - 192.168.1.92 (for localmode)
  - test-amd64
