config:
    # image: ttmetro/config
    build: .
    restart: unless-stopped
    privileged: true
    ports:
        - 8000:80
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.supervisor-api: 1
    environment:
        - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    volumes:
        - config:/config
