name: Docker Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
      list-files: json
    steps:
    # For pull requests it's not necessary to checkout the code
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Find changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dockers: "services/**"

  # JOB to build and test each of modified packages
  build:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo folders ${{ fromJSON(steps.filter.outputs.changes_files) }}
