name: Docker Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

for file in `git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]*% //g' | awk -F/ 'BEGIN {OFS="/"} {print $1,$2,""}'`; do
    echo File $file
    if [ -f $file/Dockerfile ]; then
        echo Dockerfile!
    fi
done

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      build_image: ${{ steps.filter.outputs.build_image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Check for modified services
        id: check_files
        run: |
          echo "list of modified files"
          git diff --name-only HEAD^ HEAD
          echo "check for Dockfiles"
          for file in `git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]*% //g' | awk -F/ 'BEGIN {OFS="/"} {print $1,$2,""}'`; do
              echo File $file
              if [ -f $file/Dockerfile ]; then
                  echo Dockerfile! at $file/Dockerfile
                  echo "::set-output name=build_image::true"
              fi
          done

  build:
    name: Build
    needs: changes
    if needs.check.outputs.build_image == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Matrix
      - run: echo folders ${{ fromJSON(steps.filter.outputs.build_image) }}