name: Docker Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.filter.outputs.build_files}}
    steps:
    - uses: actions/checkout@v3 
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
        list-files: json

        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
        filters: |
          build:
            - 'services/**'
    - name: File List
      if: ${{ steps.filter.outputs.builds == 'true' }}
      run: echo ${{ steps.filter.outputs.build_files }}

  build:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.filter.outputs.folders) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Matrix
      - run: echo folders ${{ fromJSON(steps.filter.outputs.folders) }}