name: Docker Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2   
      id: filter
      with:
        filters: |
          dockers: services/**
          actions: .github/**

  # JOB to build and test each of modified packages
  build:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
        version: [12, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo version ${{ matrix.version }}
      - run: echo package ${{ matrix.package }}
      - run: echo outputs ${{ fromJSON(needs.changes.outputs.packages) }}
