name: Docker Image CI

on:
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "ide49-base-notebook/**"
      - "Dockerfile"
      - "Makefile"
  push:
    paths:
      - "**/Dockerfile"
      - ".github/**"
    branches:
      - main
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Overview
        run: echo "Hello from Overview!"
