image: ttmetro/scipy-notebook
restart: unless-stopped
privileged: true
labels:
    io.balena.features.dbus: 1
    io.balena.features.supervisor-api: 1
environment:
    - UDEV=on
    - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    - JUPYTER_PORT=8893
http_port: 8893
# ports:
#     - 7000-7999
volumes:
    - iot-home:/home/iot
    {{ all_volumes() }}
depends_on:
    - config